from agente_2w.enums.enums import (
    TipoDeVerdade,
    EtapaFluxo,
    StatusSessao,
    NivelConfirmacao,
    OrigemContexto,
    StatusItemProvisorio,
    TipoEntrega,
    FormaPagamento,
    StatusPedido,
    Confianca,
    Direcao,
    Remetente,
    Posicao,
)
